### ISSUE TITLE
Scope Service on sync

### ISSUE THREAD

**Issue by volbrene** [hbagdi/deck#106]
Hello, is it possible to set a scope to a kong.yaml file. 

Reason: If i have two applications in ci pipelines, the first one i would deploy will overwrite the second service. First I execute the `deck diff` and then `deck sync`. But the problem is, that deck check the config of complete kong not only on specific service.

**Comment by hbagdi** [comment]
I think what you are looking for is Distributed configuration using decK:
https://github.com/hbagdi/deck/blob/master/docs/guides/distributed-configuration.md

You can use tagging to manage only a sub-set of configuration.

**Comment by volbrene** [comment]
You're my man. Thank you very much. That's exactly what I was looking for.

Best deployment tool for kong :)
