### ISSUE TITLE
Plugins on Routes not working

### ISSUE THREAD

**Issue by volbrene** [hbagdi/deck#108]
Hello,
I would like to add a Plugin to a specific route, but the plugin will not actived.

Can you tell me, whats the Problem is? Or is this a bug?

kong.yaml:
`
_info:
  select_tags:
    - managed-by-deck
services:
  - name: test
    host: example.com      # Need to get host danamicly via pipeline
    tags:
      - managed-by-deck
    routes:
      - name: test-unprotected
        paths:
          - /login
        strip_path: true
        methods:
          - GET
      - name: test-protected
        paths:
          - /posts
        strip_path: true
        methods:
          - POST
        plugins:
          - name: acl
            config:
              whitelist:
                - group1
          - name: jwt
            config:
              maximum_expiration: 3000
              claims_to_verify:
              - exp

    plugins:
      - name: rate-limiting
        config:
          day: null
          fault_tolerant: true
          hide_client_headers: false
          hour: null
          minute: 100
          month: null
          second: null
          year: null
        run_on: first
        protocols:
          - http
          - https
`

**Comment by hbagdi** [comment]
I think you are running into #104. Can you please upgrade to v0.6.2, which fixes it.

**Comment by volbrene** [comment]
Fixed it, thank you very much :) And thank you for the nice deployment tool for Kong :)
