### ISSUE TITLE
Version 0.7.1 errors with Error: reading Kong version: No Major.Minor.Patch elements found

### ISSUE THREAD

**Issue by Evangelinexx** [hbagdi/deck#117]
In the latest version (0.7.1), we have found that it errors out when trying to do a diff or a sync with the following error:

```
Error: reading Kong version: No Major.Minor.Patch elements found
```

This does not occur in previous versions (we are using v0.7.0 with no problems for now)

Here are examples of the commands we are running that fail with that error:
```
docker run --add-host localdev.test.com.au:$ip -v ${PWD}:/tmp -w /tmp hbagdi/deck:v0.7.1 diff -s development --kong-addr http://localdev.test.com.au:8001

docker run --add-host localdev.test.com.au:$ip -v ${PWD}:/tmp -w /tmp hbagdi/deck:v0.7.1 sync -s development --kong-addr http://localdev.test.com.au:8001
```

**Comment by hbagdi** [comment]
Can you share the output of `GET /` for Kong's Admin API?

**Comment by Evangelinexx** [comment]
Here:
```
docker run --add-host localdev.test.com.au:$ip -v ${PWD}:/tmp -w /tmp hbagdi/deck:v0.7.1 ping --kong-addr http://localdev.test.com.au:8001
Successfully connected to Kong!
Kong version:  1.4.1
```

**Comment by hbagdi** [comment]
Please downgrade to 0.7.0 for now.
I'll be releasing 0.7.2 next week with the fix included in it.

Thank you for the report!

**Comment by Evangelinexx** [comment]
Thanks for the quick fix!
