### ISSUE TITLE
Allow missing name for routes

### ISSUE THREAD

**Issue by mmorel-35** [hbagdi/deck#124]
During the dump of my config I got the following error :
```
Error: route 'be176b91-3aa9-4945-85b4-54a589053bd5' does not have a name. decK needs routes to be named.
```
In Kong the route name is optional and is quite often meaningless which is why I never define one.

Deck shall follow the same constraints as Kong does.

**Comment by hbagdi** [comment]
This is a limitation from early days of decK when decK relied solely on names to identify entities and match them up together. decK has been refactored to used IDs now so this feature is certainly possible but requires fixes to various parts of code that assume that route's name is always present.

As a work-around, name the routes for now if you would like to use decK and we will fix this issue in future.

**Comment by hbagdi** [comment]
@mmorel-35 I can't reproduce this on the latest version of decK.
Which version are you using?
Can you upgrade and try again?

**Comment by mmorel-35** [comment]
@hbagdi, I'm going to try with the last version and get back to you

**Comment by mmorel-35** [comment]
With the 1.1.0 version the dump worked perfectly fine
