### ISSUE TITLE
Export jwt credential types.

### ISSUE THREAD

**Issue by mjones11** [hbagdi/deck#125]
It does not appear decK exports jwt credential types.  Steps to reproduce:

In Kong 1.4 .xx  add jwt credential types
export configuration 
examine export file for jwt information.

This issues references:
Feature request: add support for Consumer's credentials #12

**Comment by hbagdi** [comment]
It seems like you are using an outdated version of decK. Please upgrade to the latest version for this feature.

Please close this issue if your issue is resolved.

**Comment by mjones11** [comment]
Upgrading to the latest version resolved my issue.  Apparently using brew, installed an earlier version.
