### ISSUE TITLE
Multiple Files in a Folder for Different Workspace Throwing Error on Validate, Diff and Sync

### ISSUE THREAD

**Issue by gansa1986** [hbagdi/deck#126]
Folder has multiple workspace files dumped from the Kong cluster.
APG.yaml  default.yaml  demo.yaml  mvp.yaml

Modified one service in the demo workspace.

Tried deck validate -s . , deck diff -s .

Both results in Error entity already exists.

Can you please what am I doing wrong in this?

**Comment by hbagdi** [comment]
You can export all workspaces to separate files but then you need to sync them individually.

So do instead `deck sync -s demo.yaml`.
Please close the issue if your issue is resolved.

**Comment by hbagdi** [comment]
Closing due to lack of response.
