### ISSUE TITLE
Distributed configuration skips plugin

### ISSUE THREAD

**Issue by next-albertoblanco** [hbagdi/deck#129]
I have noticed that when working with distributed configuration, dump does not export plugins of routes and service . However, general dump actually does it.
The same happens when syncing if you specify plugins in exported yaml and kong server actually has them.

Test case:

1. $> deck dump --select-tag foo
2. generated kong.yaml does not contains plugins
3. $> mv kong.yaml kong_foo.yaml
4. $> deck dump
5. Copy all services and routes to kong_foo.yaml (after _info tag)
6. $> mv  kong_foo.yaml kong.yaml
7. $> deck diff
8. It will try to create plugins of services and routes of given tag
9. $> deck sync
10. Kong returns 409 error since all plugins already exists

From my example
$ deck diff --select-tag foo
creating plugin acl for route b74a5183-8140-4ec5-a323-245011e751a3
creating plugin acl for route fe970025-b272-44d3-b464-5f0dc3193309
creating plugin acl for route 012f3665-08fd-47cb-8f89-3766471d6246
creating plugin acl for route 3032099c-93e1-4a07-828d-92176581efb5
creating plugin acl for route 8150ba7e-d610-4a86-8192-cdd3a0fb9fd7
creating plugin acl for route d8eccfc4-aa58-41b8-b1e9-49f41f00faa0
creating plugin acl for route 347963d9-e556-4a54-a111-2a3278757b1e
creating plugin jwt for route 3032099c-93e1-4a07-828d-92176581efb5
creating plugin acl for route d6bc6eb6-304e-45d2-a3b6-d4a1df27cbba
creating plugin jwt for route afac69c4-b975-4cb7-a245-1383d143ecfb
creating plugin response-transformer for route 01be8161-d003-48e4-b74a-4bdf17e76cf2
creating plugin acl for route 3c50368d-552c-4500-9740-31861a8845a1
creating plugin jwt for route 8150ba7e-d610-4a86-8192-cdd3a0fb9fd7
creating plugin jwt for route d6bc6eb6-304e-45d2-a3b6-d4a1df27cbba
creating plugin cors for service 021099f1-49de-43e8-bc2a-28d52f254462
creating plugin jwt for route 3c50368d-552c-4500-9740-31861a8845a1
creating plugin jwt for route 347963d9-e556-4a54-a111-2a3278757b1e
creating plugin jwt for route 012f3665-08fd-47cb-8f89-3766471d6246
creating plugin acl for route afac69c4-b975-4cb7-a245-1383d143ecfb
creating plugin acl for route 662354f9-df6a-424f-87d4-7e52f5b39a0f
creating plugin jwt for route d8eccfc4-aa58-41b8-b1e9-49f41f00faa0
creating plugin jwt for route fe970025-b272-44d3-b464-5f0dc3193309
creating plugin jwt for route 662354f9-df6a-424f-87d4-7e52f5b39a0f
creating plugin jwt for route b74a5183-8140-4ec5-a323-245011e751a3
Summary:
  Created: 24
  Updated: 0
  Deleted: 0

**Comment by hbagdi** [comment]
There are a few things going on here. Let's discuss one at a time.

> generated kong.yaml does not contains plugins

Do your plugins have the tag `foo` in them?

**Comment by next-albertoblanco** [comment]
No problem at all.
I forgot to mention that I'm using Deck v1.0.1 (5550012) for Mac combined with Kong v1.2.

Regarding the question of plugins, apparently they don't have any option to specify tags. Seems that is inherit from service, route or consumer

**Comment by hbagdi** [comment]
> apparently they don't have any option to specify tags.

They do. You can tag plugins in Kong.
If you don't tag them, then you can't do `deck dump --select-tag foo`

**Comment by hbagdi** [comment]
> apparently they don't have any option to specify tags.

They do. You can tag plugins in Kong.
If you don't tag them, then you can't do `deck dump --select-tag foo`

**Comment by next-albertoblanco** [comment]
Thanks for your help, Indeed I have to tag plugins.
I didn't realised since it is not in Kong documentation.

Sorry for the inconvenience
