### ISSUE TITLE
Inexistent workspace not created by sync command

### ISSUE THREAD

**Issue by jacostasym** [hbagdi/deck#130]
**deck version**
```
$ deck version
decK v1.0.2 (b9c8341)
```

**Kong version**
```
"version":"1.3.0.1-enterprise-edition"
"product_subscription":"Kong Enterprise Edition"
```

**Description**
When running deck diff or sync with a file containing a workspace that does not exist, deck returns an error stating `Error: checking workspace 'workspace-name' in Kong: Not found`.

**Expected behavior**

Documentation states:

> If a workspace is not present, decK will attempt to create the workspace before doing a sync.

https://deck.yolo42.com/guides/kong-enterprise.html

As stated by the documentation, deck should create the workspace if it does not exist.

**Comment by jacostasym** [comment]
Here is an edited snippet of the command output when run with `--verbose 2`:

```
GET /workspaces/sym-cicd48 HTTP/1.1
Host: <HOST>:9444
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Content-Length: 23
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://<HOST>:9445
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 09 Mar 2020 18:23:54 GMT
Server: kong/1.3.0.1-enterprise-edition
Vary: Origin
X-Kong-Admin-Request-Id: 0T8gq2uRcQXr3MV3IoH3mwzqMNUkAzt5

{"message":"Not found"}
Error: checking workspace 'sym-cicd48' in Kong: Not found
```

**Comment by hbagdi** [comment]
I messed up in writing documentation as far as I can remember.
I do recall the reason for not putting this logic inside 102ed5dd6f8efacfd84754fce02136059758b254.

**Comment by jacostasym** [comment]
Can you elaborate on

> workspace provisioning via an API call vs via UI has different behavior

**Comment by hbagdi** [comment]
API call creates only the workspace but if you create via Kong Manager then it creates some RBAC roles with permissions.

**Comment by hbagdi** [comment]
Closing due to lack of response. Please re-open if needed.
