### ISSUE TITLE
"Error: reading configuration from Kong: Not found" error with "deck dump" due to plugins (key-auth, basic auth, jwt, oauth2, acl, hmac-auth) not enabled.

### ISSUE THREAD

**Issue by DeclanPaulKeane** [hbagdi/deck#133]
Hey Harry,

**Summary**

When calling the "deck dump" command and you have removed one of the key-auth, basic auth, jwt, oauth2, acl, hmac-auth plugins. 

**Steps to reproduce**

1. Create kong docker-compose file 
2. Specify plugins available to kong in "plugins" config.  (Make sure Auth plugins are omitted)
3. Run "deck dump --workspace <WORKSPACE> --kong-addr http://localhost:8001/ --headers kong-admin-token:<TOKEN>"
4. Results in "Error: reading configuration from Kong: services: Not found"
	
	
**Additional Details & Logs**

When using the verbose option:

HTTP/1.1 404 Not Found
Content-Length: 23
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: <origion>:8002
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Sun, 15 Mar 2020 11:39:13 GMT
Server: kong/1.3-enterprise-edition
Vary: Origin
X-Kong-Admin-Request-Id: <id>

{"message":"Not found"}
Error: reading configuration from Kong: services: Not found

Thanks,
Declan

**Comment by hbagdi** [comment]
Seems like this should not be an issue with #121.
This is some other problem.

**Comment by hbagdi** [comment]
I can't reproduce this. Please re-open if you can with the latest version of deck.
