### ISSUE TITLE
Error to update service with retries: 0

### ISSUE THREAD

**Issue by DiegoTondim** [hbagdi/deck#134]
Hi,

I'm trying to get the diff of a service where the retries = 0 and decK is updating the value to 5.

**Steps do reproduce:**

1. service in kong with retries: 0
2. deck dump
3. deck diff

You will see the service to be updated with retries = 5.

Is there any kind of default values in some place that I could change to fix that?

**UPDATE**

I saw the same behavior in the upstream with the property **https_verify_certificate**, in kong it is "false" and after diff it is changed to "true".

**Comment by hbagdi** [comment]
It seems you are running into an issue with the default injection logic.
The constants are defined here: https://github.com/hbagdi/deck/blob/master/utils/constants.go
