### ISSUE TITLE
numerous "null" entries cause db-less to throw errors

### ISSUE THREAD

**Issue by aaronhmiller** [hbagdi/deck#135]
Had a declarative file created by `deck dump` that I was trying to use with db-less. I kept getting many errors related to entries like this:

    config:
      anonymous: null

These were created by Deck, but not tolerated by db-less Kong. Seems like either Deck shouldn't dump null values (leave them out of the output) or that db-less should understand how to handle the "null" entries.

**Comment by hbagdi** [comment]
This is a bug in Kong.
