### ISSUE TITLE
"anonymous analytics reports" not anonymous

### ISSUE THREAD

**Issue by leolb-aphp** [hbagdi/deck#136]
Hello,

I noticed you added some code to track users behavior inside the program here: https://github.com/hbagdi/deck/commit/c648a87134b76e19732b84d9cfdcc77da9642ff3#diff-4e49beab609881bfe02d81663f11d7dc

You claim that it is anonymous but it's not, any packet on the Internet contains the source IP address.

In many situations, such tracking is not acceptable, could you please remove the code that tracks user behavior or at least warn with bold lines about it and the mechanism that you implemented to disable it? I had to read into the code to find out.

Also, I am thinking you would need to ask for explicit consent rather than making it opt-out, it is much friendlier, maybe deck can ask once about it in an interactive manner with a yes/no prompt and then store the information within a temporary file in the home directory? Else, for automated uses of decK (in CI), you could probably have two flags: `--consent-analytics` and `--disable-analytics`.

Thank you

**Comment by hbagdi** [comment]
Hello @leolb-aphp,

I'll add in a document on how to disable the anonymous reporting.
The mere purpose of reporting is to figure out which features are widely used so that we can adjust the roadmap accordingly. This is very harmless and basic reporting.

For anyone else who is looking to disable this, please set the environment variable `DECK_ANALYTICS` to `off`.

**Comment by hbagdi** [comment]
This is now documented at https://github.com/hbagdi/deck/blob/master/docs/commands.md#other-settings

**Comment by leolb-aphp** [comment]
Thanks a lot @hbagdi - though I'd like to note even if it might seem harmless to you, it's not harmless for some people. Additionally your tracking takes place over plain HTTP and not HTTPS, https://github.com/hbagdi/deck/blob/cf976296250f86a0832c92fade4118023e0c5680/cmd/analytics.go#L25

**Comment by danielholden** [comment]
+1, I agree with @leolb-aphp that tracking should be opt-in, especially when used by an enterprise customer.
