### ISSUE TITLE
decK v1.1.0 not supporting mtls_auth_credentials

### ISSUE THREAD

**Issue by kallecaco3** [hbagdi/deck#148]
deck does not support mtls_auth_credentials on a consumer.
I am attaching a kong.yam which causes the folliwing error when used with deck v1.1.0:

`Error: reading file: validating file content: 1 errors occurred:
	consumers.0: Additional property mtls_auth_credentials is not allowed
`
using `kong config db_import kong.yaml` works with the same file
[kong.yaml.txt](https://github.com/hbagdi/deck/files/4580727/kong.yaml.txt)

**Comment by hbagdi** [comment]
We are adding support for this via #175.

**Comment by hbagdi** [comment]
Added in https://github.com/hbagdi/deck/commit/b1b6633f1296346168dcc2b8d003367f9fcff03c
