### ISSUE TITLE
deck sync failed to propagate changes from a existing file into a new kong installation

### ISSUE THREAD

**Issue by dgonzalezc** [hbagdi/deck#149]
When trying to propagate changes from a existing dump generated with deck to a new/empty kong 1.2 + postgres 9.6 deck sync failed with the following error:
creating consumer cl-consumer-test
creating service cl-backoffice-order-status
creating service webscraper_blumix
creating service super_cl_picking_orderhistory_preprod_service
creating service super_cl_bnf_control_orders
creating service super_cl_syg_rewards_service_dev
Error: 1 errors occurred:
        while processing event: {Create} failed: 400 Bad Request {"message":"schema violation (custom_id: length must be at least 1)","name":"schema violation","fields":{
"custom_id":"length must be at least 1"},"code":2}

deck sync with --verbose 2
{"next":null,"data":[]}
creating consumer cl-consumer-test
PUT /consumers/1b31d0cb-1d1d-4e25-818e-9dbae3a3005e HTTP/1.1
Host: 192.168.99.100:8001
User-Agent: Go-http-client/1.1
Content-Length: 90
Content-Type: application/json
Accept-Encoding: gzip

{"id":"1b31d0cb-1d1d-4e25-818e-9dbae3a3005e","custom_id":"","username":"cl-consumer-test"}
HTTP/1.1 400 Bad Request
Content-Length: 155
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 08 May 2020 23:33:55 GMT
Server: kong/1.2.0

{"message":"schema violation (custom_id: length must be at least 1)","name":"schema violation","fields":{"custom_id":"length must be at least 1"},"code":2}

deck diff after sync
Summary:
  Created: 2639
  Updated: 0
  Deleted: 0

Steps to recreate:
- deck dump from existing kong 1.2 with data
- delete kong 1.2 container + postgres 9.6 container
- create new kong 1.2 container + postgres 9.6 container
- deck sync from dump file previously created

Aditional info:
- docker toolbox
- kong database postgres 9.6
- decK v1.1.0 (acdb161)

**Comment by hbagdi** [comment]
Can you share the file generated (redact any sensitive info)?

**Comment by hbagdi** [comment]
It seems like you have `custom_id: ""` which is the root of the problem. Please remove that line and you should be good to go. I don't know why that was generated in the first place.
Can you do `deck dump --verbose 2` on the first cluster and share the output?

**Comment by dgonzalezc** [comment]
there is one line generated in the dump file:
- custom_id: ""
  username: cl-consumer-test
  keyauth_credentials:
  - key: rHhmUVJHdoctHMhsl48zD4bOenn6rRRh
  acls:
  - group: cl-consumer-test

i changed - custom_id: "" line to - custom_id: "some" and it work
Summary:
  Created: 2639
  Updated: 0
  Deleted: 0

$ deck diff --kong-addr http://192.168.99.100:8001
Warning: please note that changes in password of basic-auth credentials are not detected by decK!!
Summary:
  Created: 0
  Updated: 0
  Deleted: 0

let me do deck dump --verbose 2 and i share with you

**Comment by dgonzalezc** [comment]
Harry,

i attach the result of the deck dump command and the dump file generated


Thanks for the help


Atte.
David González Cortez.
☎ +56992258037

**Comment by hbagdi** [comment]
The attachment won't carry over via email. Please attach it via Github UI.

**Comment by dgonzalezc** [comment]
ok

[dump_log.TXT](https://github.com/hbagdi/deck/files/4610831/dump_log.TXT)

**Comment by hbagdi** [comment]
I see.
Please remove the ` "custom_id": ""` and change it to null instead. That will fix your problem.
Kong shouldn't allow for empty strings in custom_id. If it does, that's a bug in Kong.

**Comment by hbagdi** [comment]
Closing this, please re-open if needed. Thanks!
