### ISSUE TITLE
Best practice for managing certificates outside of deck

### ISSUE THREAD

**Issue by matthewbednarski** [hbagdi/deck#15]
Is there currently any flag or strategy available for not deleting all the certificates inside Kong on each `deck sync` run?

If not, what would be a possible strategy for managing the certificates separately?

**Comment by hbagdi** [comment]
That's currently not possible. We do have a `--skip-consumers` flag.
We do have tagging support coming into deck in future which will make it possible to solve this problem as deck will manage only a subset of entities in Kong and not all of them.

Meanwhile, a `--skip-certificates` flag could solve this problem. PR welcome!

**Comment by hbagdi** [comment]
With 0.4.0, decK can manage only a subset of entities in Kong using the selectTag functionality, which leverages the tagging feature released with Kong 1.1.
