### ISSUE TITLE
Using deck with Cassandra datastore causes 409 errors

### ISSUE THREAD

**Issue by StuAtKong** [hbagdi/deck#154]
deck runs Admin API calls too fast for Cassandra to propagate changes to all nodes. This causes intermittent 409 errors when the Cassandra nodes do not have the data yet for subsequent API calls. Request to add a configurable delay to deck, similar to `db_update_propagation`, that will allow Cassandra to catchup

**Comment by dowster** [comment]
We’ve also run into this issue and have mitigated it with the —parallelism 1 switch.

**Comment by cello86** [comment]
We already tested the parallelism to to 1 but with a big number of changes the 409 error appeared in a intermittent way.

**Comment by hbagdi** [comment]
Tracking the fix for this in #160 to fix this issue.
`--parallelism 1` can solve the problem only if your C* cluster is properly tuned and has enough resources.
