### ISSUE TITLE
deck dump doesn't work

### ISSUE THREAD

**Issue by nickstatka777** [hbagdi/deck#163]
Hello, 
I met the problem. I've installed deck 2 days ago, I believe I have the latest version =) 
So, when I ping the kong, I get a successful response:

```
# deck ping --kong-addr http://10.11.1.2:8001/

Successfully connected to Kong!
Kong version:  1.4.3
```

As I see ping works with remote kong too;

Then I try to dump the current configuration, as this described in the docs and get the following, please note I try different examples:

```
# deck dump --kong-addr http://10.11.1.2:8001/ --verbose 2 

GET //services?size=1000 HTTP/1.1
Host: 10.11.1.2:8001
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


HTTP/1.1 404 Not Found
Content-Length: 23
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Sun, 31 May 2020 14:10:39 GMT
Server: kong/1.4.3
X-Kong-Admin-Latency: 1

{"message":"Not found"}
Error: Not found
```

What is wrong? As I understand dump must work as for particular services, routes, etc. as for the whole configuration.

**Comment by mmorel-35** [comment]
Hi @nickstatka777, have you heard of the issue #161, try removing the trailing slash to see if it is solving your problem.

**Comment by nickstatka777** [comment]
Hi @mmorel-35 grand thanks, it really works)
