### ISSUE TITLE
Deck version is not up-to-date in Kong website. 

### ISSUE THREAD

**Issue by mmorel-35** [hbagdi/deck#165]
On [Kong web page for deck](https://docs.konghq.com/hub/kong-inc/deck/), the version of Deck is 0.4.0, which is misleading to the creation of issues that shouldn't happen.

**Comment by hbagdi** [comment]
Work is in progress by the docs team at Kong, Inc. to address this problem.
The docs for decK are undergoing a major refresh currently.

**Comment by hbagdi** [comment]
This is updated now.
