### ISSUE TITLE
can direct use deck sync to config kong?

### ISSUE THREAD

**Issue by majulong** [hbagdi/deck#21]
I applied deck to kong k8s.
here is my configmap:
![image](https://user-images.githubusercontent.com/45955327/59673561-14e35000-91f4-11e9-937f-31b362b1427c.png)
here is my Dockerfile
![image](https://user-images.githubusercontent.com/45955327/59673619-2fb5c480-91f4-11e9-8b1f-9533c2bbe6c6.png)
here is my kong-deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: kong-test:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres.default.svc.cluster.local
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        command: 
        - "/bin/sh"
        - "-ecx"
        - | 
          cd /etc/kong  && \
          # sleep 111111 && \
          kong start --v && \
          ./deck sync && \
          kong stop -v && \
          cd / && \
          ./docker-entrypoint.sh kong docker-start
        volumeMounts:
        - name: kongconfig
          mountPath: /etc/kong/kong.yaml
          subPath: kong.yaml
      volumes:
      - name: kongconfig
        configMap:
          name: kongconfig
and the result:
![image](https://user-images.githubusercontent.com/45955327/59673896-af439380-91f4-11e9-8f62-b9d5aac8d94f.png)
seams that services r1,r2,r3 all fail.
could you please help me to figure out what's wrong?
@davidcv5

**Comment by hbagdi** [comment]
Could you post the logs of your container here?

**Comment by majulong** [comment]
here is log, seems the postgreSQL has errors
![Uploading image.png…]()

**Comment by majulong** [comment]
![image](https://user-images.githubusercontent.com/45955327/59825477-b7234500-9366-11e9-8180-f01604609a0e.png)

**Comment by majulong** [comment]
I create kong_migration_cassandra.yaml  once more, and now another error show up, 
![image](https://user-images.githubusercontent.com/45955327/59826487-fe123a00-9368-11e9-84e5-0d6db3471fd5.png)

**Comment by majulong** [comment]
emmmm, have u apply deck to k8s? @hbagdi, there are a lot of problems

**Comment by hbagdi** [comment]
@majulong This is not how you should be using decK with Kong.
Spin up Kong inside k8s and then use a `Job` in k8s to sync up the configuration to Kong.

**Comment by majulong** [comment]
ok, got it! thanks a lot, it would be better to have a demo.

**Comment by hbagdi** [comment]
Please close this issue if your problem is resolved. Thank you!
