### ISSUE TITLE
Feature reqeust: add in support for reading multiple YAML files and directories

### ISSUE THREAD

**Issue by hbagdi** [hbagdi/deck#22]

**Comment by arun-a-nayagam** [comment]
Eagerly waiting for it!

**Comment by arun-a-nayagam** [comment]
Hi @hbagdi ,

How do you specify a file as an input? Or is it expected that we put all the files in the current directory and decK traverses through them?

Also an example of tags to update a service/route/consumer config would be good. 
I see in the sample kong.yaml that there are select_tags and tags, when to use what?

If there are examples or docs already available please point to them.

Thanks,
Arun
