### ISSUE TITLE
Request: Avoid reading consumers when dumping/syncing config

### ISSUE THREAD

**Issue by lmika** [hbagdi/deck#3]
Hi @hbagdi,

I have a request in regards to the sync command.  I've noticed in the code that the first thing done as part of the "sync" logic is reading all the entities of Kong, including the consumers.  I've noticed that this is done even though consumers are currently not being used as part of syncing Kong's configuration.

We will shortly be deploying Kong 1.0.3 into our production environment which has ~20,000 consumers and we're a little concerned that that many consumers may cause difficulties when using "deck" to configure Kong.

What are your thoughts of refactoring the sync logic to avoid reading consumers when dumping or syncing Kong's configuration; either by doing something similar to [kongfig](https://github.com/mybuilder/kongfig) by providing a flag, or by ignoring them altogether until there is a need to add support for configuring plugins on consumers?

If you like, I can contribute a PR which does one of these things, but I would be interested in knowing which direction you would like to take before I start changing things.

Thanks,

Leon

**Comment by hbagdi** [comment]
Hi @lmika,

Support for syncing consumers is coming next week, I was actually working on it while you opened up this issue.
It makes sense in most Kong deployments to keep consumers out of the declarative configuration of Kong, so I'll add in support for a flag (`--skip-consumers`) to skip syncing/exporting consumers.

With support for tags in Kong 1.1, it will be possible to use a `selector` tag in `deck` to manage only a subset of entities in Kong using one configuration file, at which point such `--skip-consumers` flag won't be necessary. 


For now, if you want to PR a change where `deck` doesn't export all the consumers, that should be good to merge: https://github.com/hbagdi/deck/blob/master/dump/dump.go#L147 and I'll take care of the flag approach in my feature branch for consumers.

Sounds good?

**Comment by lmika** [comment]
Thanks for that, @hbagdi.  That sounds good to me.  There's no immediate need for it now so I'm happy to wait for the `--skip-consumers` flag to become available.

Thanks again.  I'll close this issue now.
