### ISSUE TITLE
How to ignore SSL certs errors?

### ISSUE THREAD

**Issue by zoobab** [hbagdi/deck#4]
Hi,

Is there an option to ignore SSL certs errors?

I am running kong on openshift with an external route, and I have this error:

```
$ ./deck dump --kong-addr https://esteemed-hedgehog-kong-admin.kong.svc.cluster.local:8444
Error: Get https://esteemed-hedgehog-kong-admin.kong.svc.cluster.local:8444/services?size=1000: x509: certificate is valid for localhost, not esteemed-hedgehog-kong-admin.kong.svc.cluster.local
```

I made a similar script yesterday to dump the config:

https://github.com/zoobab/kongdump

with curl -k to ignore SSL problems.

**Comment by hbagdi** [comment]
@zoobab Please use `--tls-skip-verify` command line option to disable TLS cert check.

Please close this issue if it resolves your problem.
