### ISSUE TITLE
Emit a warning log when basic-auth credentials are being diffed or synced

### ISSUE THREAD

**Issue by hbagdi** [hbagdi/deck#49]
Add a warning log when decK is being used to sync basic-auth credential, notifying the user that decK will not detect change in the password

**Comment by svenwal** [comment]
Could there be a parameter to switch off that warning?

**Comment by hbagdi** [comment]
There isn't one at the moment. But, the code ensures that the warning is
emitted only once even if there are multiple basic-auth credentials. The
reasoning behind it is to always keep the user aware of this behavior.

There is a quiet mode which emits no warning or info logs at all.
