### ISSUE TITLE
Dumped yaml is not directly compatible with Kong 1.2 db-less

### ISSUE THREAD

**Issue by cristichiru** [hbagdi/deck#56]
Great work with this tool, It actually helped us a lot keeping track of the various changes we were doing in Kong and have configuration as source.

In some situations, DB-less seems to be a better option, as Cassandra is very heavy and PosgreSQL needs more config to be replicated.

So, having `kong.yaml` as a ConfigMap in a Kubernetes deployment, automatically replicated by ETCD and mounted in the Kong pods - is an attractvie solution.

Doing a dump using deck, is not immediately usable in Kong. To make it work, I had to:
- [x] Add the header `_format_version: "1.1"`.
- [ ] Remove all the keys having as value **null** string.
- [x] SNI must be in the format `name: sni-value` instead of just the sni value as it is currently, because Kong "expecst a record".

So, could you consider implementing for dump:
1. Adding the header by default when writing, ignore during reading
2. Empty/null values should actually be omitted from the dump
3. SNIs preceeded by `name: ` keyword:
    ```yaml
    snis:
    - name: some-host.com
    - name: other-host.com
    ```

**Comment by hbagdi** [comment]
> Adding the header by default when writing, ignore during reading

This is already done and will be available in v0.5.0

> Empty/null values should actually be omitted from the dump

Could you give an example of when this was problematic? decK already omits writing anything that has is null.

> SNI must be in the format name: sni-value instead of just the sni value as it is currently, because Kong "expecst a record".

Kong should have been able to handle this out of the box.
I'll talk to the Kong team to see if we can include this in Kong itself or add it to decK.

Thank you for the feedback!

**Comment by cristichiru** [comment]
Thanks for the quick reply.

1. 👍 

2. It actually does not omit them :) A snippet from the deck dump:
    ```yaml
    plugins:
    - name: cors
        config:
        credentials: false
        exposed_headers: null
        headers: null
        max_age: null
    ```
    using `deck sync` works without any issues, however, loading this yaml in a dbless deployment (tried with Kong 1.2), Kong will complain that expects a numeric value, or whatever data type the null field is supposed to be.


3. Kong fails to handle this, and in my opinion, since Kong is the more complex piece of software, it makes more sense that deck accommodate to Kong requirements sooner, rather than having Kong team fix this :)

---
Currently I have an ugly but working shell script, that depends on [yq](https://github.com/mikefarah/yq) utility:
```bash
FILE=output.yaml

## Get the snis of the first element in the certificates array, prefix it with 'name: ' and prepare it as a yq merge script
## $1 - filename
## $2 - certificates array index
yq_snis() {
    OUT=`yq r $1 "certificates[$2].snis" | grep -vP '^null$'`
    [[ -z "$OUT" ]] && return
    echo "$OUT" | sed -E 's,^- ,- name: ,' | sed "1i certificates[$2].snis:"
}

deck --kong-addr $KONG_ADMIN_URL dump -o $FILE
[[ $? -ne 0 ]] && \
    echo "[WARNING] Deck dump failed for $KONG_ADMIN_URL, proceeding to process existing $FILE"

echo '_format_version: "1.1"' > $FILE.dbless
sed -E 's,(.*-)?\s*[^:]+:\s*null,\1 ,g' $FILE | yq r - >> $FILE.dbless
IDX=0
OUT=`yq_snis $FILE.dbless $IDX`
while [[ -n "$OUT" ]]; do
    ## Update the yaml in place
    echo "$OUT" | yq w -i -s - $FILE.dbless
    IDX=`expr $IDX + 1`
    OUT=`yq_snis $FILE.dbless $IDX`
done

```

**Comment by hbagdi** [comment]
Thank you for sharing the configuration.
Let me try to experiment what can be done here.

Meanwhile, Kong 1.3 is shipping this week and it contains `kong config db_export` command to export all your entities, which can then be consumed by a DB-less Kong node.

**Comment by hbagdi** [comment]
Update: I'm making some slow progress towards this issue. #87 will fix (3) in the above list.

I've still to look into a fix for (2). I'm going to tackle it after v0.6.0 is out.

**Comment by hbagdi** [comment]
This is no longer a problem with Kong 1.4.0.
Kong works fine with empty/null values present in the config file.
