### ISSUE TITLE
bug(feature?): should allow same `target.Target` for different upstreams

### ISSUE THREAD

**Issue by zeeshen** [hbagdi/deck#57]
Currently, [GetStateFromContent](https://github.com/hbagdi/deck/blob/master/file/reader.go#L45) returns a `duplicate target definitions found for: ...` error when different upstreams have same target. 

It's not rare that different services sharing the same group of pods in Kubernetes. Such restrictions causes the kubernetes-ingress-controller stop working. Maybe we can use `${upstream.id}/${target.Target}` here as the `id` in `TargetsCollection`?

**Comment by hbagdi** [comment]
Fixed in https://github.com/hbagdi/deck/commit/b6265c3a6207ead319d94cfdceba9760ffe4adaf
