### ISSUE TITLE
Workspace deck

### ISSUE THREAD

**Issue by anoopswsib** [hbagdi/deck#70]
How can I use workspace with diff and sync. I exported file from one workspace and I need to make changes to URLs for services and then need to import into another workspace. Can we do that

**Comment by hbagdi** [comment]
Yes, you should be able to accomplish that using:
```
deck dump -w myworkspace1
# edit the kong.yaml file and change the workspace name to `myworkspace2`
deck sync
```
This should replicate your configuration in the second workspace.
