### ISSUE TITLE
Feature Request: sync/diff command - use of '-' indicates to read from stdin

### ISSUE THREAD

**Issue by matthewbednarski** [hbagdi/deck#8]
Hi,

It would be nice if the `sync` and `diff` commands would read try to read from `stdin` if a '`-`' (_dash_) is indicated on the command line.

**Comment by hbagdi** [comment]
Hi @matthewbednarski 

This would certainly be a great addition, PR welcome!

**Comment by matthewbednarski** [comment]
Hi @hbagdi,

I'm not a go programmer but I'll try to dedicate some time to it. 

Btw, I love this program!
