### ISSUE TITLE
Deck support serial and parallel sync

### ISSUE THREAD

**Issue by cello86** [hbagdi/deck#85]
Hi,
we're trying to use deck on our Kong installation with some routes and randomly we noticed error into the routes updates. It seems related to the concurrent updates on database side. Is it possible to use a serial sync?

Thanks,
Marcello

**Comment by hbagdi** [comment]
The parallelism is hard-coded as 10:
https://github.com/hbagdi/deck/blob/21fd1af6442e5ec20f33718c28e4110562f09e95/solver/solver.go#L26

PR welcome to make this configurable.
